DDDNB/Controllers/StudentController.cs
using Application;
using Application.Interfaces;
using AutoMapper;
using Domain.Commands;
using Domain.Notifications;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace UI.Web.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentAppService _studentAppService;
        private readonly IMapper _maooer;

        public readonly DomainNotificationHandler _notifications;

        public StudentController(IStudentAppService studentAppService,IMapper mapper, INotificationHandler<DomainNotification> notification)
        
        {
            _studentAppService = studentAppService;
            _notifications = (DomainNotificationHandler?)notification;

        }
        public IActionResult Index()
        {
            return View(_studentAppService.GetAll());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(StudentViewModel studentViewModel)
        {
            try
            {
                Guid id = Guid.NewGuid();
                studentViewModel.Id = id;
                // 视图模型验证
                if (!ModelState.IsValid)
                    return View(studentViewModel);

                #region klk
#if DEBUG
                //RegisterStudentCommand registerStudentCommand = new RegisterStudentCommand(
                //    studentViewModel.Name,
                //    studentViewModel.Email,
                //    studentViewModel.BirthDate,
                //    studentViewModel.Phone);
                //if (!registerStudentCommand.IsValid())
                //{
                //    List<string> errorInfos = new List<string>();
                //    foreach (var error in registerStudentCommand.ValidationResult.Errors)
                //    {
                //        errorInfos.Add(error.ErrorMessage);
                //    }
                //    ViewBag.ErrorData = errorInfos;
                //    return View(studentViewModel);
                        
                //}
#endif
                #endregion
                // 执行添加方法
                _studentAppService.Register(studentViewModel);

                if (!_notifications.HasNotifications())
                {
                    ViewBag.success = "Student Registered!";

                }

                return View(studentViewModel);
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }
    }
}

DDDNB/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace DDDNB.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DDDNB/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DDDNB.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

DDDNB/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DDDNB.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

DDDNB/ViewComponents/AlertsViewComponent.cs
using Domain.Notifications;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace UI.Web.ViewComponents
{
    public class AlertsViewComponent : ViewComponent
    {
        //private IMemoryCache _cache;
        private readonly DomainNotificationHandler _notifications;
        public AlertsViewComponent(
            //IMemoryCache cache
            INotificationHandler<DomainNotification> notifications
            )
        {
            //_cache = cache;
            _notifications = (DomainNotificationHandler)notifications;
        }
        /// <summary>
        /// Alerts 视图组件
        /// 可以异步，也可以同步，注意方法名称，同步的时候是Invoke
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var errorData = await Task.FromResult(_notifications.GetNotifications());

            errorData?.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

DDDNB/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DDDNB/Views/Shared/Components/alerts/Default.cshtml
@if (ViewData.ModelState.ErrorCount > 0)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="msgRetorno">Alert! Something went wrong:</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
}

@if (!string.IsNullOrEmpty(ViewBag.Sucesso))
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="msgRetorno">@ViewBag.Sucesso</h3>
    </div>
}

DDDNB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DDDNB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DDDNB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">DDDNB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item" >
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DDDNB - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DDDNB/Views/Student/Create.cshtml
@using Application
@model StudentViewModel
@{
    ViewData["Title"] = "Register new Student";
}
<h2>@ViewData["Title"]</h2>
<form asp-controller="Student" asp-action="Create">
    <div class="form-horizontal">
        <hr />
        @* 将经典验证摘要替换为自定义视图组件作为标记助手 *@

       @* 方式一(可用，但不推荐) @await Component.InvokeAsync("Alerts")*@

        <!-- 如果使用这个方法，请记得在_ViewImports.cshtml 中，导入@addTagHelper "*, UI.Web" -->
        <vc:alerts/>

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BirthDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
        </div>

        @*<div class="form-group">
            <label asp-for="Address.Province" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address.Province" class="form-control" />
                <span asp-validation-for="Address.Province" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address.City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address.County" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address.County" class="form-control" />
                <span asp-validation-for="Address.County" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address.Street" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
        </div>*@

        <div class="form-group">
            <label asp-for="Province" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Province" class="form-control" />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="County" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="County" class="form-control" />
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Street" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>

DDDNB/Views/Student/Index.cshtml
@using Application
@model IEnumerable<StudentViewModel>
@{
    ViewData["Title"] = "Student Management";
}
<div>
    <h2>@ViewData["Title"]</h2>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Register New" class="glyphicon glyphicon-plus-sign"></span> Register New
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BirthDate)
                </th>
                <th>户籍</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BirthDate)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.Address.Province)
                            @Html.DisplayFor(modelItem => item.Address.City)
                            @Html.DisplayFor(modelItem => item.Address.County)
                            @Html.DisplayFor(modelItem => item.Address.Street)*@

                        @Html.DisplayFor(modelItem => item.Province)
                        @Html.DisplayFor(modelItem => item.County)
                        @Html.DisplayFor(modelItem => item.City)
                        @Html.DisplayFor(modelItem => item.Street)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-warning">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>

                        <a asp-action="Details" asp-route-id="@item.Id" title="Details" class="btn btn-primary">
                            <span class="glyphicon glyphicon-search"></span>
                        </a>

                        <a asp-action="Delete" asp-route-id="@item.Id" title="Delete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>

                        <button type="button" class="btn btn-purple viewbutton" title="History" data-id="@item.Id" data-toggle="modal" data-target="#studentHistory">
                            <span class="glyphicon glyphicon-time"></span>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="modal fade" id="studentHistory" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">student Data History</h4>
            </div>
            <div class="modal-body">
                <p id="studentHistoryData"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@section scripts
    {
    <script type="text/javascript">

        $(".viewbutton").on("click", function () {
            var customerId = $(this).data('id');
            $("#studentHistoryData").html("");
            $.ajax({
                url: "/history/" + customerId,
                cache: false
            }).done(function (data) {
                var formatHtml = "<table class='table table-striped'>";
                formatHtml += "<thead><th>Action</th><th>When</th><th>Id</th><th>Name</th><th>E-mail</th><th>Birth Date</th><th>By User</th></thead>";
                
                for (var i = 0; i < data.length; i++) {
                    var change = data[i];
                    formatHtml += "<tr>";
                    formatHtml += "<td>" + change.action + "</td>";
                    formatHtml += "<td>" + change.when + "</td>";
                    formatHtml += "<td>" + change.id + "</td>";
                    formatHtml += "<td>" + change.name + "</td>";
                    formatHtml += "<td>" + change.email + "</td>";
                    formatHtml += "<td>" + change.birthDate + "</td>";
                    formatHtml += "<td>" + change.who + "</td>";
                    formatHtml += "</tr>";
                }
                formatHtml += "</table>";
                $("#studentHistoryData").html(formatHtml);
            });
        });
    </script>
}